### ISSUE TITLE
RuntimeError: Working outside of application context

### ISSUE THREAD

**Issue by exploide** [AdrianVollmer/PowerHub#58]
Suddenly a weird error occurs when starting powerhub. Since nothing has changed for a while, maybe it is according to some updated dependency?

```console
$ powerhub --auth xxx:xxx 192.168.122.244
I 2022-10-20 13:30:40 Importing modules...
Traceback (most recent call last):
  File "/home/user/repos/PowerHub/venv/bin/powerhub", line 8, in <module>
    sys.exit(main())
  File "/home/user/repos/PowerHub/venv/lib/python3.10/site-packages/powerhub/__main__.py", line 8, in main
    PowerHubApp().run(background=background)
  File "/home/user/repos/PowerHub/venv/lib/python3.10/site-packages/powerhub/app.py", line 66, in __init__
    self.init_db()
  File "/home/user/repos/PowerHub/venv/lib/python3.10/site-packages/powerhub/app.py", line 111, in init_db
    init_db(db)
  File "/home/user/repos/PowerHub/venv/lib/python3.10/site-packages/powerhub/sql.py", line 18, in init_db
    _db.create_all()
  File "/home/user/repos/PowerHub/venv/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 868, in create_all
    self._call_for_binds(bind_key, "create_all")
  File "/home/user/repos/PowerHub/venv/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 839, in _call_for_binds
    engine = self.engines[key]
  File "/home/user/repos/PowerHub/venv/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 628, in engines
    app = current_app._get_current_object()  # type: ignore[attr-defined]
  File "/home/user/repos/PowerHub/venv/lib/python3.10/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
```

Here a list of the dependencies I got after a fresh install.

```console
$ python --version
Python 3.10.7

$ pip freeze
aesedb==0.1.0
aiosmb==0.4.3
aiowinreg==0.0.7
asn1crypto==1.5.1
asyauth==0.0.6
asysocks==0.2.2
attrs==22.1.0
Automat==20.2.0
bidict==0.22.0
cffi==1.15.1
cheroot==8.6.0
click==8.1.3
colorama==0.4.5
constantly==15.1.0
cryptography==38.0.1
defusedxml==0.7.1
Flask==2.2.2
Flask-SocketIO==5.3.1
Flask-SQLAlchemy==3.0.2
greenlet==1.1.3.post0
hyperlink==21.0.0
idna==3.4
incremental==22.10.0
itsdangerous==2.1.2
jaraco.functools==3.5.2
Jinja2==3.1.2
json5==0.9.10
MarkupSafe==2.1.1
minidump==0.0.21
minikerberos==0.3.3
more-itertools==9.0.0
msldap==0.4.6
oscrypto==1.3.0
PowerHub @ file:///home/user/repos/PowerHub
prompt-toolkit==3.0.31
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pycryptodomex==3.15.0
pyOpenSSL==22.1.0
pypykatz==0.6.2
python-engineio==4.3.4
python-magic==0.4.27
python-socketio==5.7.2
PyYAML==6.0
service-identity==21.1.0
six==1.16.0
SQLAlchemy==1.4.42
tqdm==4.64.1
Twisted==22.8.0
typing_extensions==4.4.0
unicrypto==0.0.9
watchdog==2.1.9
wcwidth==0.2.5
Werkzeug==2.2.2
winacl==0.1.5
WsgiDAV==4.0.2
zope.interface==5.5.0
```

**Comment by AdrianVollmer** [comment]
Quick fix:

```diff
diff --git a/setup.py b/setup.py
index 04c7b5d..3cc54c6 100644
--- a/setup.py
+++ b/setup.py
@@ -23,7 +23,7 @@ setuptools.setup(
         'cryptography',
         'Flask>=1.0.2',
         'Flask-SocketIO>=3.1.2',
-        'flask-sqlalchemy>=2.1',
+        'flask-sqlalchemy>=2.1<3',
         'pyOpenSSL',
         'pypykatz>=0.2.2',
         'python-magic',
```
