### ISSUE TITLE
Missing positional argument when starting powerhub

### ISSUE THREAD

**Issue by 0x00xx** [AdrianVollmer/PowerHub#61]
I am running powerhub like this:
`powerhub 192.168.1.32`

But get the following error:
```
I 2023-04-25 17:48:32 Generating new Diffie-Hellman parameters
Traceback (most recent call last):
  File "/usr/local/bin/powerhub", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/powerhub/__main__.py", line 13, in main
    PowerHubApp(args).run(background=background)
  File "/usr/local/lib/python3.8/dist-packages/powerhub/app.py", line 72, in __init__
    self.init_flask()
  File "/usr/local/lib/python3.8/dist-packages/powerhub/app.py", line 118, in init_flask
    from powerhub.flask import app as flask_blueprint
  File "/usr/local/lib/python3.8/dist-packages/powerhub/flask.py", line 22, in <module>
    from powerhub.hiddenapp import hidden_app
  File "/usr/local/lib/python3.8/dist-packages/powerhub/hiddenapp.py", line 13, in <module>
    from powerhub.dhkex import DH_G, DH_MODULUS, DH_ENDPOINT
  File "/usr/local/lib/python3.8/dist-packages/powerhub/dhkex.py", line 73, in <module>
    generate_diffie_hellman_params()
  File "/usr/local/lib/python3.8/dist-packages/powerhub/dhkex.py", line 21, in generate_diffie_hellman_params
    parameters = dh.generate_parameters(generator=g, key_size=KEY_SIZE)
TypeError: generate_parameters() missing 1 required positional argument: 'backend'
```

I installed it like suggested with pip.

**Comment by 0x00xx** [comment]
works after installing it again

**Comment by AdrianVollmer** [comment]
This was probably due to  the `cryptography` dependency. It needs to be at least v35. I'll define this requirement in the pyproject.toml. Thanks for reporting.
