### ISSUE TITLE
Startup fails: PatternMatchingEventHandler.__init__() takes 1 positional argument but 5 were given

### ISSUE THREAD

**Issue by edermi** [AdrianVollmer/PowerHub#66]
**Describe the bug**
Startup fails: 
~~~
I 2024-08-28 07:36:35 Generating new Diffie-Hellman parameters
I 2024-08-28 07:36:35 Importing modules...
Traceback (most recent call last):
  File "/home/pentest/.local/bin/powerhub", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pentest/.local/share/pipx/venvs/powerhub/lib/python3.11/site-packages/powerhub/__main__.py", line 13, in main
    PowerHubApp(args).run(background=background)
    ^^^^^^^^^^^^^^^^^
  File "/home/pentest/.local/share/pipx/venvs/powerhub/lib/python3.11/site-packages/powerhub/app.py", line 80, in __init__
    set_up_watchdog()
  File "/home/pentest/.local/share/pipx/venvs/powerhub/lib/python3.11/site-packages/powerhub/modules.py", line 183, in set_up_watchdog
    my_event_handler = PatternMatchingEventHandler(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PatternMatchingEventHandler.__init__() takes 1 positional argument but 5 were given
~~~

**To Reproduce**
1. `pipx install powerhub`
2. `powerhub 192.168.x.x`
3. See error. Also fails with `--auth`, but in my understanding only providing IP is the minimal requirement for running PowerHub

**Expected behavior**
PowerHub starts up

**Logs (please complete the following information):**
Python log:
```
powerhub -d 192.168.x.x
I 2024-08-28 07:45:28 dhkex.py:19 Generating new Diffie-Hellman parameters
D 2024-08-28 07:45:28 tools.py:106 Loaded secret key: 2jKcO4vqedhhiekxTK3pdpcVjSrI5uzu
I 2024-08-28 07:45:28 modules.py:59 Importing modules...
Traceback (most recent call last):
  File "/home/pentest/.local/bin/powerhub", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pentest/.local/share/pipx/venvs/powerhub/lib/python3.11/site-packages/powerhub/__main__.py", line 13, in main
    PowerHubApp(args).run(background=background)
    ^^^^^^^^^^^^^^^^^
  File "/home/pentest/.local/share/pipx/venvs/powerhub/lib/python3.11/site-packages/powerhub/app.py", line 80, in __init__
    set_up_watchdog()
  File "/home/pentest/.local/share/pipx/venvs/powerhub/lib/python3.11/site-packages/powerhub/modules.py", line 183, in set_up_watchdog
    my_event_handler = PatternMatchingEventHandler(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PatternMatchingEventHandler.__init__() takes 1 positional argument but 5 were given

```

**Python versions (please complete the following information):**
 - Output of `python --version`: Python 3.11.9
 - Output of `pip freeze` (After installing it in a fresh venv with pip instead of pipx, which has the same issue): 
~~~
attrs==24.2.0
Automat==24.8.1
bidict==0.23.1
blinker==1.8.2
certifi==2024.7.4
cffi==1.17.0
charset-normalizer==3.3.2
cheroot==10.0.1
click==8.1.7
constantly==23.10.4
cryptography==43.0.0
defusedxml==0.7.1
dnspython==2.6.1
Flask==3.0.3
Flask-SocketIO==5.3.6
Flask-SQLAlchemy==3.1.1
greenlet==3.0.3
h11==0.14.0
hyperlink==21.0.0
idna==3.8
incremental==24.7.2
itsdangerous==2.2.0
jaraco.functools==4.0.2
Jinja2==3.1.4
json5==0.9.25
MarkupSafe==2.1.5
more-itertools==10.4.0
powerhub==2.0.8
pyasn1==0.6.0
pyasn1_modules==0.4.0
pycparser==2.22
pyOpenSSL==24.2.1
python-engineio==4.9.1
python-magic==0.4.27
python-socketio==5.11.3
PyYAML==6.0.2
requests==2.32.3
service-identity==24.1.0
simple-websocket==1.0.0
SQLAlchemy==2.0.32
Twisted==24.7.0
typing_extensions==4.12.2
urllib3==2.2.2
watchdog==5.0.0
Werkzeug==3.0.4
WsgiDAV==4.3.3
wsproto==1.2.0
zope.interface==7.0.3
~~~

Thanks for your great work as well as sharing it with the community!

**Comment by AdrianVollmer** [comment]
Until I can fix this, you can install watchdog 4 in powerhub's virtual environment:

```console
pip install 'watchdog<5.0'
```

**Comment by edermi** [comment]
I installed it directly from source as there's no new release on PyPi yet. Can confirm it works again, thanks a lot!
